# Generated by Django 4.1.7 on 2023-02-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forgottenCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerUserId', models.CharField(max_length=30)),
                ('clientUserId', models.CharField(blank=True, max_length=30, null=True)),
                ('createdTime', models.DateTimeField()),
                ('closedTime', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerUserId', models.CharField(max_length=30)),
                ('clientUserId', models.CharField(blank=True, max_length=30, null=True)),
                ('createdTime', models.DateTimeField()),
                ('closedTime', models.DateTimeField(blank=True, null=True)),
                ('goods', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerUserId', models.CharField(max_length=30)),
                ('clientUserId', models.CharField(blank=True, max_length=30, null=True)),
                ('createdTime', models.DateTimeField()),
                ('closedTime', models.DateTimeField(blank=True, null=True)),
                ('goods', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
